let podaci = [
  {
    id: 1,
    naziv_proizvoda: "Vzk univerzalna krema 100ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 209.99,
    opis: "Univerzalna krema za negu i hidrataciju svih tipova kože, osim izrazito masne i problematične kože.Pakovanje sadrži 100ml.",
    slika: "images/Slika1.webp",
  },
  {
    id: 2,
    naziv_proizvoda: "Velnea dnevna krema protiv bora sa koenzimom Q10 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 449.99,
    opis: "DNEVNA KREMA ZA LICE PROTIV BORA  sa koenzimom Q10 je lagana formulacija, namenjena dnevnoj nezi kože lica. Koenzim Q10 je snažan antioksidans , koji ublažava vidljive posledice starenja kože, sprečava nastanak novih bora i štiti kožu od negativnih spoljašnjih uticaja. Krema sadrži argan ulje,,Vitamin E i glicerin koji zajedno sa koenzimom Q10 doprinose borbi protiv starenja kože.Svakodnevnom upotrebom, koža lica postaje osvežena, hidrirana, mekša i blistavija. Način upotrebe naneti ujutru na čistu kožu lica, laganim kružnim pokretima.",
    slika: "images/slika3.webp",
  },
  {
    id: 3,
    naziv_proizvoda: "Bioten Vitamin C 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 599.99,
    opis: "Bioten dnevna krema protiv bora i za prosvetljenje tena sa vitaminom C sadrži 90% sastojaka prirodnog porekla i pruža koži potrebnu dnevnu dozu energije. Vitamin C obnavlja kožu i ujednačava ten na prirodan nacin. Štiti kožu od oksidativnog stresa i podstičesintezu kolagena sprečavajući prevremeno stvaranje bora. Visoka tolerancija i stabilna formulacija štite kožu od iritacija. Sadrži 100% prirodni ekstrakt limete i pomorandžekoji su bogati antioksidansima, vitamin B3, D pantenol i hijaluronsku kiselinu.",
    slika: "images/slika2.webp",
  },
  {
    id: 4,
    naziv_proizvoda: "Garnier Bio Anti-age ulje za lice 30 ml",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 1109.99,
    opis: "S organskim eteričnim uljem lavande, organskim uljem argana i vitaminom E. Za sve tipove kože, čak i za osetljivu kožu. Momentalno hrani i omekšava kožu. Naš proizvod je serti?kovano organskog porekla. Naša lavanda se uzgaja u Francuskoj. Miris 100% prirodnog porekla.",
    slika: "images/slika5.webp",
  },
  {
    id: 5,
    naziv_proizvoda: "Hada Labo Tokyo gel krema za lice 50 ml",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 2309.99,
    opis: "Luksuzna dnevna i noćna krema je savršena kombinacija kreme i seruma sa delikatnom i laganom gelastom teksturom. Svojim delovanjem povećava sveukupni kvalitet kože, vraćajući joj prirodnu zaglađenost .Zbog izuzetno visoke koncentracije Super Hijaluronske kiseline, veoma intenzivno hidrira kožu, pružajući dugoročnu hidrataciju blago ispunjavajući sve neravnine i nepravilnosti dajući koži mekan, nežan i gladak izgled. Bez parabena, boja parfema I mineralnih ulja.",
    slika: "images/slika6.webp",
  },
  {
    id: 6,
    naziv_proizvoda:
      "Ziaja acai berry antioksidativni micelarni piling gel za lice 200ml",
    kategorija: "lice",
    podkategorija: "piling",
    cena: 579.99,
    opis: "Sadrži aktivne prirodne  supstance – acai bobice, kalcijum glukonat, vitamin C, cink coceth sulfat, D-pantenol, glicerin, celulozni acetat (biorazgradive piling čestice celuloze). Veganski proizvod. Ne sadrži gluten.",
    slika: "images/slika7.webp",
  },
  {
    id: 7,
    naziv_proizvoda: "Garnier Hyaluronic Aloe tonik za lice 200 ml",
    kategorija: "lice",
    podkategorija: "tonik",
    cena: 499.99,
    opis: "Tonik sa 96% sastojaka prirodnog porekla* obogaćen organskom aloe verom i hijaluronskom kiselinom. E?kasno uklanja ostatke šminke, čineći kožu savršeno čistom i svežom.",
    slika: "images/slika8.webp",
  },
  {
    id: 8,
    naziv_proizvoda: "Garnier Bio Thyme tonik za lice 150 ml",
    kategorija: "lice",
    podkategorija: "tonik",
    cena: 649.99,
    opis: "Sa organskim eteričnim uljem timijana i salicilnom kiselinom. Za kombinovanu do masne kože. Uklanja nečistoće i čini ten kože ?nijim. Naš proizvod je serti?kovano organski. Naš timijan se uzgaja u Francuskoj. Miris 100% prirodnog porekla.",
    slika: "images/slika9.webp",
  },
  {
    id: 9,
    naziv_proizvoda: "Bioten vitamin C maska u maramici 20ml",
    kategorija: "lice",
    podkategorija: "maska",
    cena: 229.99,
    opis: "Bioten vitamin C maska u maramici revitalizuje, vraća energiju dehidriranoj koži i prosvetljava njen ten. Sadrži vitamin C, niacinamid (vitamin B3) i ekstrakt pomorandže, koji imaju izuzetna svojstva regeneracije i prosvetljenja tena. Pogodno za sve tipove kože. Dermatološki testirano.",
    slika: "images/slika4.webp",
  },
  {
    id: 10,
    naziv_proizvoda:
      "Garnier Skin Naturals Eye Tissue maska za oči protiv tamnih krugova",
    kategorija: "lice",
    podkategorija: "maska",
    cena: 249.99,
    opis: "OSVEŽAVAJUĆA MASKA ZA OČI U MARAMICI za vidljivo smanjenje kesica ispod očiju i tamnih podočnjaka.",
    slika: "images/slika10.webp",
  },
  {
    id: 11,
    naziv_proizvoda: "Bioderma Atoderm blagi gel za tuširanje 1L",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 1969.99,
    opis: "Zahvaljujući svojim hidrirajućim sastojcima, Atoderm Blagi gel za tuširanje čini kožu mekom i zaštićenom.Njegova umirujuća svojstva smanjuju osećaj zatezanja kože.",
    slika: "images/slika11.webp",
  },
  {
    id: 12,
    naziv_proizvoda: "Nuxe Prodigieux Riche čarobno suvo ulje za telo",
    kategorija: "telo",
    podkategorija: "ulje",
    cena: 3489.99,
    opis: "Huile Prodigieuse® Riche Obogaćeno čarobno suvo ulje, 100 ml za negu kose, lica i tela za suvu kožu. Čarobno suvo ulje je obogatilo svoju formulu sa čak 30% više ulja makadamije, te je namenjeno suvoj koži lica i tela. ",
    slika: "images/slika12.webp",
  },
  {
    id: 13,
    naziv_proizvoda: "Nuxe čaroban mirisni losion za telo 200ml",
    kategorija: "telo",
    podkategorija: "losion",
    cena: 1829.99,
    opis: "Hidratizuje i hrani kožu, čini je svilenkasto mekom i blistavom. Za Čarobno negovanu, obnovljenu i ulepšanu kožu lica i tela te kosu",
    slika: "images/slika13.webp",
  },
  {
    id: 14,
    naziv_proizvoda: "VZK Mleko za negu tela 200 ml",
    kategorija: "telo",
    podkategorija: "losion",
    cena: 299.99,
    opis: "Formulacija na bazi retinola, tokoferola i kvalitetnih biljnih ulja jojobe i masline. Sadrži hidratantni kompleks prirodnog porekla koji omogućava dugotrajnu hidrataciju kože tela. Mleko je namenjeno za negu svih tipova kože, a posebno za negu izrazito suve i osetljive kože.",
    slika: "images/slika14.webp",
  },
  {
    id: 15,
    naziv_proizvoda:
      "Vichy roll-on dezodorans bez belih tragova i žutih fleka, 50 ml",
    kategorija: "telo",
    podkategorija: "dezodorans",
    cena: 1529.99,
    opis: "Njezine antiperspirantne supstance zajedno sa umirujućim kopleksom Proline Cutei vašu kožu 48 sati efikasno štite od prekomernog znojenja i obezbeđuju joj izuzetnu toleranciju.",
    slika: "images/slika15.webp",
  },
  {
    id: 16,
    naziv_proizvoda: "Eucerin AtopiControl Losion za telo 250ml",
    kategorija: "telo",
    podkategorija: "losion",
    cena: 2129.99,
    opis: "Eucerin AtopiControl Losion za telo je losion za svakodnevnu negu koji se brzo upija. Specijalno je formulisan da umiri i ntenzivno hidrira iziritiranu kožu koja svrbi. Obogaćen je likokalkonom A koji umiruje, ceramidima i omega masnim kiselinama koji jačaju barijernu funkciju kože, smanjuju suvoću i svrab i produžavaju period mirovanja izmedju upalnih faza atopijskog dermatitisa.",
    slika: "images/slika16.webp",
  },
  {
    id: 17,
    naziv_proizvoda: "Garnier Color Sensation Boja za kosu 5.51 Ruby",
    kategorija: "kosa",
    podkategorija: "farba",
    cena: 399.99,
    opis: "Prva boja za kosu iz Garnier-a sa bisernim ekstraktom i Cvetnim Uljem za SENZACIONALNU BOJU! Njena jedinstvena formula sadrži intenzivne pigmente. snažna, odgovarajućeg tona i izuzetno dugotrajna. prekrivanje sedih vlasi.",
    slika: "images/slika17.webp",
  },
  {
    id: 18,
    naziv_proizvoda: "Garnier Olia boja za kosu 10.1",
    kategorija: "kosa",
    podkategorija: "farba",
    cena: 489.99,
    opis: "OLIA BOJA ZA KOSU Moć ulja za maksimalne performanse boje i vidljivo bolji kvalitet kose.",
    slika: "images/slika18.webp",
  },
  {
    id: 19,
    naziv_proizvoda:
      "LOréal Professionnel Paris Mythic Oil ulje za sve tipove kose 100ml",
    kategorija: "kosa",
    podkategorija: "ulje",
    cena: 2429.99,
    opis: "Profesionalno višenamensko ulje za negu kose. Formula ovog proizvoda je obogaćena visokom koncentracijom negujućih ulja za kosu. Visoka koncentracija arganovog ulja u formuli pruža negu kosi i štiti vlas. Lagana i tečna tekstura proizvoda se jednostavno nanosi, pružajući osećaj svilenkaste kose od korena do krajeva. Ulje je idealno koristiti nakon pranja kose, pre ili nakon feniranja.",
    slika: "images/slika19.webp",
  },
  {
    id: 20,
    naziv_proizvoda: "Afrodita Hair Care Arganovo ulje 50 ml",
    kategorija: "kosa",
    podkategorija: "ulje",
    cena: 659.99,
    opis: "Bogata mešavina prirodnih ulja dragocenog argana, makadamije i kokosa obnavlja vrhove kose, štiti, bogato neguje, dubinski obnavlja, intenzivno hidrira i osigurava sjajnu kosu.",
    slika: "images/slika20.webp",
  },
  {
    id: 21,
    naziv_proizvoda: "Ziaja cupuacu šećerni piling za telo 200ml",
    kategorija: "telo",
    podkategorija: "piling",
    cena: 755.99,
    opis: "Prvi proizvod ove vrste u Ziaja ponudi, čijim se korišćenjem dobijaju brzi rezultati izgleda negovane i zdrave kože.Sadrži kristalni šećer i ljuske oraha zatvorene u bazi, bogate tečnim emolijentima i mikrovoskom.Omekšava, zaglađuje i smanjuje hrapavost i suvoću kože, te pruža dugotrajan prijatan efekat i prelep miris na koži.Preporučuje se za telo, ruke i stopala.",
    slika: "images/slika21.webp",
  },
  {
    id: 22,
    naziv_proizvoda:
      "Vichy Dercos energetski sampon protiv opadanja kose 400ml",
    kategorija: "kosa",
    podkategorija: "sampon",
    cena: 2159.99,
    opis: "Dercos energetski šampon protiv opadanja kose sa aktivnim sastojkom aminexil-om® i vitaminima B3/B5*/B6. Kosa je ojačana i izgleda punija. Opadanje kose je povezano sa preranim starenjem korena vlasi. Ovaj šampon obogaćen je patentiranom molekulom aminexil i vitaminima, pa kosi daje vitalnost i snagu da se bori protiv opadanja. kosa je revitalizovana i vidljivo manje lomljiva i krhka. Ovaj šampon je idealan dodatak liniji za muškarce i žene dercos aminexil clinical 5. U slučaju kontakta sa očima odmah temeljno isperite. *pro-vitamin B5.",
    slika: "images/slika22.webp",
  },
  {
    id: 23,
    naziv_proizvoda: "Frudia Tone Up krem sa zaštitinim faktorom SPF50+ 50g",
    kategorija: "telo",
    podkategorija: "krema za suncanje",
    cena: 859.99,
    opis: "Zaštitna krema koja posvetljuje kožu bez sjaja,  istovremeno joj poboljšava tonus i štiti od UV zračenja. 6 tipova vočnih ulja nežno prodire u kožu, posvetljuje je i daje prirodan izgled. Takođe se može koristiti kao baza za podizanje tona kože usled blagog prijanjanja na kožu nakon čega njena površina ostaje glatka.",
    slika: "images/slika23.webp",
  },
  {
    id: 24,
    naziv_proizvoda: "ALMA K hranljiva noćna krema za sve tipove kože 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 1899.99,
    opis: "Ultra-umirujuc´e i hranljivo pojačanje preko noc´i za sve tipove kože lica. Snažan kompleks minerala Mrtvog mora, ši putera, ulja jojobe bogatog omega masnim kiselinama i ekstrakta kamilice oživljava i umiruje umornu kožu - za prelep i jedar jutarnji sjaj.",
    slika: "images/slika24.webp",
  },
  {
    id: 25,
    naziv_proizvoda: "ALMA K bogata hranljiva maska za lice 100ml",
    kategorija: "lice",
    podkategorija: "maska",
    cena: 1599.99,
    opis: "Bogata maska za lice, zasnovana na hranljivom kompleksu biljnih ekstrakata i ulja, minerala Mrtvog mora i vitamina E koji ostavlja osec´aj čistog, svilenkastog zadovoljstva.",
    slika: "images/slika25.webp",
  },
  {
    id: 26,
    naziv_proizvoda:
      "Nivea creme care gel za tuširanje 500ml +GRATIS Nivea creme soft gela za tuširanje 250ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 605.99,
    opis: "Super ponuda - NIVEA Cream Care gel za tusiranje 500ml uz poklon NIVEA Cream Soft gel za tusiranje 250ml. Iskoristi ovu ograničenu ponudu.",
    slika: "images/slika26.webp",
  },
  {
    id: 27,
    naziv_proizvoda: "Fa Ipanema nights ženski dezodorans roll on 50ml",
    kategorija: "telo",
    podkategorija: "dezodorans",
    cena: 299.99,
    opis: "Deo roll on sa mirisom cveta noćnog jasmina i 100% prirodnim ekstraktom marakuje. Kompleks aktivne svežine pruža do 48h mirisne zaštite. Ne sadrži soli aluminijuma.",
    slika: "images/slika27.webp",
  },
  {
    id: 28,
    naziv_proizvoda: "Ziaja bundeva i đumbir šećerni piling za telo 300ml",
    kategorija: "telo",
    podkategorija: "piling",
    cena: 799.99,
    opis: "Karamelizovani šećerni piling za telo namenjen je svim tipovima kože. Nežno uklanja mrtve ćelije kože te ostavlja prelep, slasni miris karamelizovane bundeve i začinskog đumbira. Savršeno omekšava, zaglađuje i neguje kožu. Stvara nežni zaštitni sloj koji štiti kožu od dehidracije, te nisu potrebna dodatna sredstva za hidrataciju nakon korišćenja ovog pilinga.",
    slika: "images/slika28.webp",
  },
  {
    id: 29,
    naziv_proizvoda:
      "LOréal Professionnel Serie Expert Absolut Repair Huile Ulje za kosu 90ml",
    kategorija: "kosa",
    podkategorija: "ulje",
    cena: 2490.0,
    opis: "Višenamensko ulje, za normalnu i osetljivu kosu. Obogaćeno uljem pšeničnih klica.",
    slika: "images/slika300.webp",
  },
  {
    id: 30,
    naziv_proizvoda:
      "Eveline Oils of Nature suvo ulje za lice i telo + serum za podmlađivanje 125ml",
    kategorija: "kosa",
    podkategorija: "ulje",
    cena: 399.99,
    opis: "Proizvod sa 11 prirodnih ulja ( Inca inchi ulje, ulje marule, arganovo ulje, ulje kukui oraha, ulje avokada, makadamije, badema, suncokreta, ruzmarina i semena grožđa) savršeno hidrira, hrani i neguje kožu lica i tela.",
    slika: "images/slika29.webp",
  },
  {
    id: 31,
    naziv_proizvoda: "Avene Oxitive serum 30ml",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 4385.99,
    opis: "Antioksidativni zaštitni serum.",
    slika: "images/slika31.webp",
  },
  {
    id: 32,
    naziv_proizvoda:
      "Nuxuriance Ultra Globalni obnavljajući anti-age serum 30 ml",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 5039.99,
    opis: "Globalni obnavljajući anti-age serum. Obnavlja, podmlađuje, ujednačava ten i briše pigmentacijske mrlje. Za lice, vrat i dekolte / Za sve tipove kože. Dnevna i/ili noćna nega.",
    slika: "images/slika32.webp",
  },
  {
    id: 33,
    naziv_proizvoda: "Azeta organski bebi losion za lice i telo SPF50 0m+ 50ml",
    kategorija: "telo",
    podkategorija: "losion",
    cena: 1285.99,
    opis: "Organski bebi i dečiji losion sa visokim faktorom zaštite (SPF50) od sunca za lice i telo, deluje efektivno kao barijera za UVA i UVB zrake. Vlaži i štiti kožu od sunčanja. Ne sadrži boje i paraben. Odabirom ove kreme štite vašu kožu I kožu vaše bebe i istovremeno čuvate more (hemijske kreme za sunčanje, koje obično koriste potrošači, vrlo su toksične za vodene organizme i školjke). Ovaj proizvod sadrži samo prirodne mineralne sastojke sa cinkovim oksidom i bazom titanijum-dioksida u Non Nano obliku. Odsustvo hemijskih jedinjenja čini proizvod vrlo sigurnim i pogodnim za posebno osjetljivu kožu. HIPOALERGIJSKI, BEZ GLUTENA, PARABENA, SULFATA, POGODAN OD ROĐENJA.",
    slika: "images/slika33.webp",
  },
  {
    id: 34,
    naziv_proizvoda: "ALMA K suvo ulje za telo 110ml",
    kategorija: "telo",
    podkategorija: "ulje",
    cena: 1299.99,
    opis: "Suvo ulje za telo formulisano da dubinski hidrira kožu, sa uljima avokada, masline, argana i slatkog badema, vitaminom E i mineralima Mrtvog mora. Prirodna umirujuc´a hidratacija ostavlja svilenkasto-glatki nahranjen osec´aj.",
    slika: "images/slika34.webp",
  },
  {
    id: 35,
    naziv_proizvoda: "ALMA K dvofazni stimulativni piling za telo 250ml",
    kategorija: "telo",
    podkategorija: "piling",
    cena: 1299.99,
    opis: "Dvofazni piling za telo sadrži piling granule soli Mrtvog mora i hranljiva ulja semenki grožđa i slatkog badema. Namirisan belim čajem i nerolijem, ostavlja savršen osec´aj glatke, prefinjene i obnovljene kože.",
    slika: "images/slika35.webp",
  },
  {
    id: 36,
    naziv_proizvoda: "ALMA K tonik za lice 200ml",
    kategorija: "lice",
    podkategorija: "tonik",
    cena: 1299.99,
    opis: "Delikatni tonik bez alkohola čisti i uravnotežuje vaš ten bez isušivanja kože lica. Bogat vodom iz Mrtvog mora i hranljivim ekstraktima, pore izgledaju manje vidljive, za gladak, osvežen i blistav izgled.",
    slika: "images/slika36.webp",
  },
  {
    id: 37,
    naziv_proizvoda: "ALMA K serum za besprekoran sjaj kože lica 30ml",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 1699.99,
    opis: "Snažan, glatki serum koji oživljava i pojačava prirodni sjaj vaše kože. Lagana kremasta formula je prožeta aktivnim biljnim matičnim ćelijama koje koži pružaju snagu regeneracije. Zajedno sa hranljivim mineralima Mrtvog mora, sokom od aloe vere i antioksidantnim ekstraktom zelenog čaja, ovaj serum pruža esencijalnu dozu ishrane za vrhunski besprekoran izgled kože lica.",
    slika: "images/slika37.webp",
  },
  {
    id: 38,
    naziv_proizvoda: "ALMA K blatna maska za dubinsko čišćenje lica 100ml",
    kategorija: "lice",
    podkategorija: "maska",
    cena: 1599.99,
    opis: "Detoksirajte kožu maskom od blata Mrtvog mora koja upija višak sebuma i uklanja nečistoc´e. Formula za pročišc´avanje sa morskim algama bogatim hranljivim sastojcima, ekstraktom krastavca i uljem semena boražine koja ostavlja mek i gladak osec´aj.",
    slika: "images/slika38.webp",
  },
  {
    id: 39,
    naziv_proizvoda: "Elseve Extraordinary Oil Balsam za kosu (200 ml)",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 399.99,
    opis: "Extraordinary balsam, svojim bogatom teksturom dopunjuje ishranu koju kosa dobija već prilikom nanošenja Extraordinary šampona. Kosa je: raščešljana, blistavog sjaja, bez osećaja težine",
    slika: "images/slika39.webp",
  },
  {
    id: 40,
    naziv_proizvoda:
      "Garnier Fructis Sos Repair regenerator za oštećenu kosu 200ml",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 319.99,
    opis: "SOS Repair obnavlja površinu vlasi i ispunjava pukotine nastale spoljnim delovanjem. Jednogodišnja površinska oštećenja su obnovljena nakon samo tri upotrebe*.",
    slika: "images/slika40.webp",
  },
  {
    id: 41,
    naziv_proizvoda:
      "Head&Shoulders Classic Clean šampon za kosu protiv peruti 360ml",
    kategorija: "kosa",
    podkategorija: "sampon",
    cena: 559.99,
    opis: "Head & Shoulders Classic Clean pretstavlja proizvod iz Head & Shoulders linije proizvoda koji je formulisan tako temeljno čisti kosu i borise protiv peruti.",
    slika: "images/slika41.webp",
  },
  {
    id: 42,
    naziv_proizvoda: "Head&Shoulders Ocean šampon za kosu protiv peruti 225ml",
    kategorija: "kosa",
    podkategorija: "sampon",
    cena: 409.99,
    opis: "Head & Shoulders Ocean Energy šampon pretstavlja proizvod iz Head & Shoulders linije proizvoda dizajniran da vrati život umornoj i beživotnoj kosi.",
    slika: "images/slika42.webp",
  },
  {
    id: 43,
    naziv_proizvoda:
      "LOreal Paris Men Expert Hydra Energetic krema za negu lica 50 ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 1019.99,
    opis: "LOreal Men Expert Hydra Energetic  krema za lice predstavlja proizvod iz LOreal linije proizvoda, koja je specijalno namenjena nezi muškaraca.",
    slika: "images/slika43.webp",
  },
  {
    id: 44,
    naziv_proizvoda:
      "LOreal Paris Men Expert Magnesium Defense dezodorans u spreju 150ml",
    kategorija: "telo",
    podkategorija: "dezodorans",
    cena: 429.99,
    opis: "Visoko efikasni dezodorans obogaćen magnezijum oksidom za 48h zaštite od neprijatnih mirisa. Napravljen od samo 5 sastojaka. Hipoalergeno.Formula obogaćena magnezijum oksidom, mineralom koji je prirodno prisutan u ljudskom telu i poznat po svom snažnom upijajućem svojstvu, efikasno pruža potpunu zaštitu od vlažnosti** i neprijatnih mirisa. 0% alkohola*. Testirano pod dermatološkom kontrolom i na osetljivoj koži.",
    slika: "images/slika44.webp",
  },
  {
    id: 45,
    naziv_proizvoda:
      "LOreal Paris Men Expert Thermic Resist Dezodorans u spreju 150ml",
    kategorija: "telo",
    podkategorija: "dezodorans",
    cena: 429.99,
    opis: "Thermic Resist– antiperspirant zasnovan na  Ceramic-System tehnologiji, štiti od znojenja pri visokim temperaturama čak do 45°C*.",
    slika: "images/slika45.webp",
  },
  {
    id: 46,
    naziv_proizvoda: "Phytorelax keratin maska za rekonstrukciju kose 250ml",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 899.99,
    opis: "Phytorelax Keratin maska za dubinsku rekonstrukciju kose sa tečnim keratinom.",
    slika: "images/slika46.webp",
  },
  {
    id: 47,
    naziv_proizvoda: "Phytorelax Argan šampon za negu kose 250ml",
    kategorija: "kosa",
    podkategorija: "sampon",
    cena: 899.99,
    opis: "Idealan za pranje i negu čak i za najoštećeniju i krtu kosu, daje momentalnu mekoću, svilenkast osećaj i blistavost.",
    slika: "images/slika47.webp",
  },
  {
    id: 48,
    naziv_proizvoda: "La Roche Posay Toleriane losion za čišćenje lica, 200 ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 1765.99,
    opis: "La Roche Posay Toleriane losion predstavlja proizvod za čišćenje i uklanjanje šminke. Tečna tekstura obogaćena glicerinom koji vlaži kožu.Stroga načela formulacije, minimalna količina sastojaka sa ciljem smanjenja opasnosti od alergija kože.",
    slika: "images/slika48.webp",
  },
  {
    id: 49,
    naziv_proizvoda:
      "La Roche-Posay lipikar kremasti gel za tuširanje obogaćen lipidima za pranje osetljive suve kože, 400 ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 2189.99,
    opis: "Veoma nežna formula za pranje tela. Bez sapuna. Bez mirisa. Bez parabena.Pomaže u obnavljanju barijere kože i uspostavljanju ravnoteže mikrobioma. Veoma nežna formula za pranje tela obogaćena Karite Buterom i Niacinamideom, udružena sa Aqua Posae Filiformisom, novim i ekskluzivno patentiranim sastojkom za delovanje na determinišuće faktore kože sklone atopiji.  ",
    slika: "images/slika49.webp",
  },
  {
    id: 50,
    naziv_proizvoda: "Bioderma sebium losion za masnu i kombinovanu kožu 200ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 2095.99,
    opis: "Sebium Lotion dugotrajno vraća ravnotežu osetljivoj kombinovanoj do masnoj koži. Trostruko dejstvo: Hidratacija koja traje 8h, regulacija sebuma i pH vrednosti kože.Sužava pore. Nekomedogen proizvod.",
    slika: "images/slika50.webp",
  },
  {
    id: 51,
    naziv_proizvoda:
      "Bioderma Node Ds+ Anti- Recidive šampon protiv peruti i svraba 125ml",
    kategorija: "kosa",
    podkategorija: "sampon",
    cena: 1855.99,
    opis: "Node DS+ kremasti šampon sadrži ekskluzivni DSactiv® kompleks dvostrukog dejstva: smanjuje rast gljivice Malassezia, čestog uzročnika peruti, a istovremeno smanjuje lučenje sebuma koji stimuliše rast ove gljivice. Moćni aktivni sastojci deluju keratoregulatorno, eliminišu upornu perut i sprečavaju njeno ponovno pojavljivanje",
    slika: "images/slika51.webp",
  },
  {
    id: 52,
    naziv_proizvoda:
      "Bioderma Sebium Mat Kontrol hidratantna matirajuća nega 30ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 2009.99,
    opis: "Višenamenski proizvod hidratacija-matiranje-ujednačen ten; vidiljivi rezultati 8h; kontinuirana efikasnost u roku od 7 dana; pogodno za osetljivu kožu; odlična podloga za šminku; brzo upijajuća tekstura; poboljšana koža iz dana u dan.",
    slika: "images/slika52.webp",
  },
  {
    id: 53,
    naziv_proizvoda:
      "Bioderma Sebium Hydra hidrantna krema za lice za masnu kožu 40ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 1615.99,
    opis: "Za masnu kožu sklonu aknama koja je oslabljana, isušena i/ili iritirana različitim tretmanima. Intenzivno hidrira.",
    slika: "images/slika53.webp",
  },
  {
    id: 54,
    naziv_proizvoda: "Bioderma Sebium Global 30ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 1769.99,
    opis: "Global deluje na biološke uzroke (prvi proizvod koji uspostavlja fiziološki kvalitet sebuma)Ciljano deluje na posledice ( redukuje hiperseboreju, ima keratolitičko dejstvo)Garantuje komplijansu (dugotrajna hidratacija-8h)Zaustavlja proces nastajanja akni.",
    slika: "images/slika54.webp",
  },
  {
    id: 55,
    naziv_proizvoda: "Bioderma Hydrabio bogata hidrantna krema 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 2179.99,
    opis: "Svakodnevno zagadjenje, stres, hladnoća itd. remete ćelijsku aktivnost kože. Kao rezultat toga, koža postaje dehidrirana, istanjena, gubi sjaj. Zbog toga je tim stručnjaka razvio Bioderma Hydrabio kremu koja trajno i dubinski hidrira i hrani, ujednačava ten i podstiče blistavost i čini kožu mekom, ostavljajući osvežavajući blagi miris.",
    slika: "images/slika55.webp",
  },
  {
    id: 56,
    naziv_proizvoda: "Noreva Aquareva piling za lice 75ml",
    kategorija: "lice",
    podkategorija: "piling",
    cena: 1725.99,
    opis: "Namenjen higijeni dehidrirane kože, vraća joj elastičnost, blistavost i mekoću. Stimuliše ćelijsku obnovu i uklanja mrtve epidermalne ćelije zahvaljujući nežnoj eksfolijaciji sitnim perlama bambusa. Hidrira kožu pomoću Hidro-esencijalnog kompleksa. Ostavlja blistav ten i nežnu, hidriranu kožu kojoj je vraćena čvrstina. Priprema kožu za dalju negu.",
    slika: "images/slika56.webp",
  },
  {
    id: 57,
    naziv_proizvoda: "Neutrogena Brightboost piling 75ml",
    kategorija: "lice",
    podkategorija: "piling",
    cena: 2899.99,
    opis: 'Neutrogena" Bright Boost piling krema za sve tipove koze: Formulisano sa A?? I prirodnim perlicama, ova krema sa dvostrukim dejstvom pomaže u uklanjanju nečistoća na umornoj koži za vidllvo blstaviji i glatkiji izgled.',
    slika: "images/slika57.webp",
  },
  {
    id: 58,
    naziv_proizvoda: "Eucerin DermoPure Piling za masnu kožu lica 100ml",
    kategorija: "lice",
    podkategorija: "piling",
    cena: 1109.99,
    opis: "Eucerin DermoPure Piling je piling za kožu sa mlečnom kiselinom deluje direktno na mestu problema bez isušivanja kože. Pogodan je za lice i telo. Mikročestice za čišćenje pora nežno skidaju izumrle ćelije sa kože, ne oštećujući je. Blago čisti kožu i uklanja šminku.",
    slika: "images/slika58.webp",
  },
  {
    id: 59,
    naziv_proizvoda:
      "NIVEA Pore Purifying 3u1 piling maska za čišćenje lica 150ml",
    kategorija: "lice",
    podkategorija: "piling",
    cena: 645.99,
    opis: "NIVEA Pore Purifying Refining 3u1 piling maska za čišćenje lica sadrži efikasnu antibakterijsku formulaciju obogaćenu priodnim ekstraktom magnolije i kaolin glinom koja:1. Čisti -uklanja sve nečistoće i duboko čisti kožu lica 2.Piling - pročićava kožu, čisti pore, pomaže u smanjivanju mrlja koje uzrokuju bakterije3. Maska -za dodatan efekat mat tena i glatke kože. Ne izaziva iritacije zbog svoje blage formulacije.",
    slika: "images/slika59.webp",
  },
  {
    id: 60,
    naziv_proizvoda: "Nivea Rice piling za čišćenje lica za mešovitu kožu",
    kategorija: "lice",
    podkategorija: "tonik",
    cena: 649.99,
    opis: "Dubinski čisti kožu zahvaljujući prirodnim sastojcima  i pruža koži blistav sjaj. INOVACIJA: 100% bio razgradive pirinčane piling čestice koje ne isušuju kožu i čine je mekom i svilenkastom na dodir. ",
    slika: "images/slika60.webp",
  },
  {
    id: 61,
    naziv_proizvoda: "Bioten cleansing gel detox charc 200ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 455.99,
    opis: "Micelarni gel za umivanje za normalnu i masnu kožu sa 100% prirodnim ugljem i prebioticima. Idealno uklanja sve vrste nečistoća sa lice, a prebitoci održavaju mikrobiološki balans na koži što doprinosi njenom zdravom izgledu.",
    slika: "images/slika61.webp",
  },
  {
    id: 62,
    naziv_proizvoda: "Afrodita Clean phase rebalance micelarna pena 150ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 765.99,
    opis: "CLEAN PHASE REBALANCE PENA. Namenjena za negu mešovite/masne kože. Temeljno čisti i odmašćuje kožu, a pritom je ne isušuje. Čuva njenu prirodnu pH ravnotežu   uklanja i šminku. Aktivni sastojci: ekstrakt limuna i hamamelisa. Ne sadrži silikone, boje. Sadrži hipoalergene parfem. Primereno za vegane.Upotreba:ujutro i uveče naneti na vlažno lice, nežno utrljati, isprati toplom vodom. Toniziranje odabranim tonikom Clean Phase. ",
    slika: "images/slika62.webp",
  },
  {
    id: 63,
    naziv_proizvoda: "Noreva Actipur Gel 400ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 2499.99,
    opis: "Actipur seboregulatorni gel je specijalno formulisan da nežno otkloni sve nesavršenosti udružene sa masnom kožom kod dece, tinejdžera i odraslih. Pogodan je za higijenu osetljive, masne i problematične kože. Blagotvorni biljni ekstrakti žalfije, čička i kresa ostavljaju pore čistim i kožu umirenu i hidriranu tokom celog dana. Bez sapuna, izuzetno blag gel koji efikasno otklanja nečistoće i reguliše produkciju sebuma na licu i telu.",
    slika: "images/slika63.webp",
  },
  {
    id: 64,
    naziv_proizvoda:
      "Vichy normaderm gel za dubinsko čišćenje masne kože, 400 ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 1915.99,
    opis: "INOVACIJA: baza za čišćenje biljnog porekla sačinjena od agenasa za stvaranje pene koji bez oštećenja dubinski čiste kožu .Novi gel za čišćenje za masnu i kožu sklonu aknama, obogaćen mineralima i probiotičkim derivatima, efikasno uklanja prljavštinu, prašinu i čestice zagađenja već prilikom prvog korišćenja.",
    slika: "images/slika64.webp",
  },
  {
    id: 65,
    naziv_proizvoda:
      "Vichy Purete Thermale Sveži gel za čišćenje osetljive kože lica 200 ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 1865.99,
    opis: "Vichy purete thermal gel za lice oslobađa kožu od svih neprijatnosti i nečistoća. Preporučuje se za isušenu kožu sa osećajem zategnutosti.",
    slika: "images/slika65.webp",
  },
  {
    id: 66,
    naziv_proizvoda: "Frudia my orchard cherry kupka za telo 350ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 1019.99,
    opis: "Višnja “body shower” temeljno čisti površinu kože, duboko prodirući u njene pore, i otklanjajući neprijatne tragove i mirise. Zahvaljujući receptu koji sadrži sastojke meda i višnje prepune vitamina, i fitocidnu komponentu, ima izuzetnu sposobnost čišćenja Vaše kože.",
    slika: "images/slika66.webp",
  },
  {
    id: 67,
    naziv_proizvoda:
      "Dove Purely Pampering Shea butter gel za tuširanje 500 ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 625.99,
    opis: "Dove Purely Pampering Shea butter gel za tuširanje predstavlja proizvod iz Dove Natrium Moisture linije proizvoda koji Vašoj koži pruža dodatnu negu i hidrataciju.",
    slika: "images/slika67.webp",
  },
  {
    id: 68,
    naziv_proizvoda: "Ziaja lemon cake želatina kupka i gel za tuširanje 260ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 699.99,
    opis: "Kupka i gel za tuširanje u formi želea, sa mirisom limunovog kolačića pruža novo, neverovatno iskustvo prilikom tuširanja• Ostavlja kožu čistom i veoma mirisnom.",
    slika: "images/slika68.webp",
  },
  {
    id: 69,
    naziv_proizvoda:
      "Ziaja Cocoa Butter gel za tuširanje sa kakao maslacem 500 ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 369.99,
    opis: "Ziaja gel za tuširanje sa kakao maslacem predstavlja proizvod poljskog brenda Ziaja koji pruža Vašoj koži potrebnu negu i hidrataciju. Intenzivno hrani i hidrira kožu, sprečava gubitak vode, što kožu čini mekom i elastičnom. Sadrži kakao maslac i provitamin B5 koji Vašoj koži pružaju dodatnu negu i hidrataciju, čineći je mekanom i nežnom na dodir.",
    slika: "images/slika69.webp",
  },
  {
    id: 70,
    naziv_proizvoda: "Ziaja cupuacu gel za tuširanje 500ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 419.99,
    opis: "Novi Cupuacu gel za tuširanje sadrži hranljive materije koje omogućavaju regeneraciju kože i smanjuju prekomerni piling.",
    slika: "images/slika70.webp",
  },
  {
    id: 71,
    naziv_proizvoda: "Velnea Young višenamensko suvo ulje za telo",
    kategorija: "telo",
    podkategorija: "ulje",
    cena: 379.99,
    opis: "Nakon nanošsenja, ostavlja kožu mekom i svilenkastom, dok zlatne čestice naglašavaju preplanulost i daju blistav izgled koži.",
    slika: "images/slika71.webp",
  },
  {
    id: 72,
    naziv_proizvoda: "Velnea Sun bifazna voda za sunčanje SPF50+ 150ml",
    kategorija: "telo",
    podkategorija: "krema za suncanje",
    cena: 1385.99,
    opis: "Bifazna voda za sunčanje koja se lako nanosi i brzo upija. Ovaj kozmetički proizvod je specijalno formulisan da štiti kožu od sunčevog zračenja. Sadrži glicerin koji pomaže vlaženju kože. Sa solarnim filterima koji pružaju zaštitu SPF50 + za zaštitu kože. UVA + UVB zaštita. Vodootporno. Dermatološki testirano.",
    slika: "images/slika72.webp",
  },
  {
    id: 73,
    naziv_proizvoda: "NIVEA SUN dečiji obojeni sprej za sunčanje SPF 50+ 200ml",
    kategorija: "telo",
    podkategorija: "krema za suncanje",
    cena: 1679.99,
    opis: "NIVEA SUN Protect & Care dečji obojeni sprej sadrži formulaciju posebno osmišljenu za osetljivu dečiju kožu. Sadrži izuzetno efikasne UVA/UVB filtere koji pružaju pouzdanu zaštitu. Štiti od štetnog uticaja sunčevih zraka. Vodootporan.",
    slika: "images/slika73.webp",
  },
  {
    id: 74,
    naziv_proizvoda: "Carroten mleko sprej kokos SPF50 200ml",
    kategorija: "telo",
    podkategorija: "krema za suncanje",
    cena: 1325.99,
    opis: "Pruža visok nivo zaštite, za kožu koja je osetljiva na sunce. Praktično i jednostavno za nanošenje, zahvaljujući formulaciji koja se brzo upija i spreju sa širokim obimom raspršivanja. Superdry system za brzo upijanje, transparentan, bez masnih i belih tragova. Pruža prijatan osećaj hlađenja do -2°C ostavljajući kožu hidriranom. Proizvod pruža četiri nivoa zaštite od širokog spektra štetnog sunčevog zračenja, koje je odgovorno za prevremeno starenje i druga oštećenja kože: UVB, UVA, infracrvenog zračenja i vidljive svetlosti. Dermatološki testirano.",
    slika: "images/slika74.webp",
  },
  {
    id: 75,
    naziv_proizvoda: "Phytocolor 9 Blond tres clair dor farba za kosu",
    kategorija: "kosa",
    podkategorija: "farba",
    cena: 1485.99,
    opis: "PHYTOCOLOR farba za kosu predstavlja spoj najnovije tehnologije i botaničkih istraživanja za sjajnu i izražajnu dugotrajnu boju. Pokriva sede vlasi već pri prvom nanošenju.",
    slika: "images/slika75.webp",
  },
  {
    id: 76,
    naziv_proizvoda:
      "Aura Velvet Ton 11A Svetlo pepeljasto plava farba za kosu",
    kategorija: "kosa",
    podkategorija: "farba",
    cena: 279.99,
    opis: "Aura Velvet ton Farba za kosu predstavlja inovativan proizvod iz Aura linije proizvoda za farbanje kose. Ova farba sadrži visoku koncentraciju pigmenata nove generacije koji garantuju sjajnu, postojanu i dugotrajnu boju za svaki tip kose. Rezultat je intenzivna boja i jaka i zdrava kosa.",
    slika: "images/slika76.webp",
  },
  {
    id: 77,
    naziv_proizvoda: "Revlon Colorsilk 55 farba za kosu",
    kategorija: "kosa",
    podkategorija: "farba",
    cena: 679,
    opis: "Revlon Colorsilk farba za kosu predstavlja jedinstven proizvod koji Vam obezbeđuje prirodan izgled, savršenu boju od korena do vrha. Osim što pojačava intenzitet boje kose, ovaj proizvod Vašoj kosi pruža definiciju i dimenzijalnost.",
    slika: "images/slika77.webp",
  },
  {
    id: 78,
    naziv_proizvoda: "Pantene Bamboo maska za kosu, 160ml",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 609.99,
    opis: "Pantene Bamboo maska za kosu koja dolazi iz kolekcije Pro-V Mikracles stvorena je za kosu kojoj je potrebno čudo! Ova maska bogata keratinom sprečava opadanje kose uzrokovano lomljenjem, garantujući i do 100% jaču kosu. ",
    slika: "images/slika78.webp",
  },
  {
    id: 79,
    naziv_proizvoda: "Pantene Biology Balance maska za kosu, 160ml",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 709.99,
    opis: "Otkrijte Pro-V Hair Biology prilagođenu mešavinu za vašu kosu. Ova osvežavajuc´a maska za kosu jača suvu  i slabu kosu. Čini kosu jačom *. Ima sastav sa vitaminom B7 i Pro-V i ne sadrži silikon.",
    slika: "images/slika79.webp",
  },
  {
    id: 80,
    naziv_proizvoda:
      "Garnier Fructis Hair Food Goji Maska za obojenu kosu 390 ml",
    kategorija: "kosa",
    podkategorija: "maska",
    cena: 715.99,
    opis: "Maska za obojenu kosu. Štiti obojenu kosu i osvežava je tokom dužeg vremena. Pakovanje: 390ml",
    slika: "images/slika80.webp",
  },
  {
    id: 81,
    naziv_proizvoda: "Garnier Bio Anti-age dnevna krema 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 919.99,
    opis: "DNEVNA NEGA ZA LICE PROTIV EFEKATA STARENJA KOŽE. S organskim eteričnim uljem lavande i antioksidantnim vitaminom E. Za sve tipove kože, čak i za osetljivu kožu. Koža je zategnutija i bore su manje vidljive. Naš proizvod je sertifikovano organski. Naša lavanda se uzgaja u Francuskoj. Miris 100% prirodnog porekla.",
    slika: "images/slika81.webp",
  },
  {
    id: 82,
    naziv_proizvoda: "Hada Labo Tokyo losion super hidrator za negu lica",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 2099.99,
    opis: "Lagani, vodenasti gel koji prodire u dublje slojeve kože, trenutno. Super Hijaluronska kislina( kompleks 3 tipa hijaluronske kiseline ) dubinski hidrira i sprečava dehidrataciju kože.",
    slika: "images/slika82.webp",
  },
  {
    id: 83,
    naziv_proizvoda: "Salvia krema kamilica i neven 30ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 649.99,
    opis: "Za posebnu negu masne i problematične kože. Bogatstvo Kamilice i Neven kreme se ogleda u moćnoj harmoniji biljaka i njihovih ulja, pčelinjeg voska, latica kamilice i nevena koje utiču na umirivanje štetnih procesa masne i problematične kože. Mlevena latice cveta kamilice i nevena pomažu u zaceljivanju postojećih upalnih procesa na koži, a redovnom upotrebom sprečavaju i nastanak novih, čineći kožu glatko mekanom, hidrantnom i bez suvišnog sjaja. Idealna kombinacija pčelinjeg voska, prirodnih eteričnih ulja kamilice, nevena, kantariona i bokvice savršeni su za negu i prevenciju upala masne i problematične kože",
    slika: "images/slika83.webp",
  },
  {
    id: 84,
    naziv_proizvoda: "Salvia krema sa devičanskim saćem 30ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 1099.99,
    opis: "Pojačava elastičnost kože i ublažava i usporava znake starenja. Pogodna i kao krema za celodnevnu negu. Isceljujuća snaga devičanskog saća, bademovog ulja i eteričnih ulja žalfije daju poseban efekat na kožu lica i dekoltea. SALVIA sa devičanskim saćem poboljšava gipkost i mekoću kože i sprečava nastanak pega i fleka na koži. Potpomaže prirodnu ravnotežu između vlažnosti i masnoće i obezbeđuje vitalnost kože. Bademovo ulje uspešno usporava i sprečava nastanak bora i ublažava postojeće. Zbog visokog sadržaja cinka efikasno regeneriše ćelijsku membranu kože i čini vaše lice mladim i jedrim. Intenzivne i brze efekte daje kao noćna krema.",
    slika: "images/slika84.webp",
  },
  {
    id: 85,
    naziv_proizvoda:
      "Embryolisse Smoothing Eye Contour Care - Podmlađujuća krema za predeo oko očiju, 15ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 2529,
    opis: "Ublažava fine linije i bore, smanjuje otečenost i tamne kolutove ispod očiju. Veoma lagana tekstura, koja sadrži hijaluronsku kiselinu, vitamine A i E i biljne ekstrakte (ulje susama, različak i hrast).",
    slika: "images/slika85.webp",
  },
  {
    id: 86,
    naziv_proizvoda:
      "Lierac Diopticerne krema za oko očiju protiv tamnih kolutova 15ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 3359.99,
    opis: "Tretman protiv svih tipova tamnih kolutova: Krema je obogaćena vitaminom C koji deluje kao antioksidans, protivupalno i prosvetljuje boju kože, dok delovanje arnike stimuliše mikrocirkulaciju i pomaže apsorpciju hematoma nastalih slabljenjem krvnih sudova. Kompleks hijaluronske kiseline i peptida (tripeptidid) stimulišu prirodnu sintezu hijaluronske kiseline u koži.",
    slika: "images/slika86.webp",
  },
  {
    id: 87,
    naziv_proizvoda: "Lierac Hydragenist hidratantni gel za oko očiju 15ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 4095.99,
    opis: "Hydragenist hidrantna krema za zonu oko očiju nežno štiti ovo osetljivo područje. Pogodna je za sve tipove kože.",
    slika: "images/slika87.webp",
  },
  {
    id: 88,
    naziv_proizvoda: "IDEAL RESOURCE prosvetljujuća krema oko očiju 15ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 7479.99,
    opis: "Ova biljna formula pomaže vidnom posvetljavanju tamnih kolutova i glačanju finih linija i bora. Kompozicija sa lubenicom, avokadom i ši buterom, hidrira i prosvetljuje, vrac´ajuc´i mladalački sjaj očima. ",
    slika: "images/slika88.webp",
  },
  {
    id: 89,
    naziv_proizvoda: "Weleda Krema oko očiju od nara 10ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 2759.99,
    opis: "Krema za zonu oko očiju za zrelu kožu, učvršćuje i poboljšava teksturu kože.",
    slika: "images/slika89.webp",
  },
  {
    id: 90,
    naziv_proizvoda:
      "La Roche-Posay REDERMIC RETINOL Intenzivni koncentrat protiv starenja za osetljivu kožu oko očiju, 15 ml",
    kategorija: "lice",
    podkategorija: "kreme za predeo oko ociju",
    cena: 3595.99,
    opis: "Inovacija za osetljive oči: Ekskuluzivni retinol kompleks sa efektom izglađivanja u kombinaciji sa kofeinom koji deluje protiv umora u tečnoj i laganoj teksture sa efektom zatezanja, pogodno za osetljive oči.",
    slika: "images/slika90.webp",
  },
  {
    id: 91,
    naziv_proizvoda: "Afrodita Red Grapes gel za tuširanje 250ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 295.99,
    opis: "Jedinstveni doživljaj tuširanja s osvežavajućim mirisom grožđa! Sa ekstraktom grožđa te ekstraktima prirodnih ulja kokosa, suncokreta i palminih jezgra čuva vlagu u koži i pomaže pri sprečavanju njenog isušivanja.",
    slika: "images/slika91.webp",
  },
  {
    id: 92,
    naziv_proizvoda:
      "Tesori di Oriente Orhideja kremasti gel za tuširanje 250 ml",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 3155.99,
    opis: "Tesori d Oriente je kompletna linija proizvoda za ličnu negu, prvi put lansirana 1997. Filozofija brenda vuče korene sa Dalekog Istoka koji je i bio inspiracija za sve sastojke i mirise ovih jedinstvenih proizvoda.",
    slika: "images/slika92.webp",
  },
  {
    id: 93,
    naziv_proizvoda:
      "FAITH IN NATURE Gel za tuširanje lavanda i geranijum 400ML",
    kategorija: "telo",
    podkategorija: "gel",
    cena: 749.99,
    opis: "• Napravljeno od 100% prirodnog mirisa.• Napravljeno od esencijalnih ulja.• Bez parabena i SLS-a.• Vegan i cruelty-free.• 99% prirodnog porekla.",
    slika: "images/slika93.webp",
  },
  {
    id: 94,
    naziv_proizvoda: "Velnea čistač za lice 2kom",
    kategorija: "lice",
    podkategorija: "čistači i masažeri",
    cena: 259.99,
    opis: "Čistač za lice.",
    slika: "images/slika94.webp",
  },
  {
    id: 95,
    naziv_proizvoda: "REVOLUTION PRO 24k Gold 28ml serum za lice",
    kategorija: "lice",
    podkategorija: "serum",
    cena: 2499.99,
    opis: "Hidratantni prajmer serum za lice sa hijaluronskom kiselinom, kolagenom, vitaminom B5 i reflektujućim česticama zlata za prozračan izgled kože lica.Smanjuje vidljivost proširenih pora i sitnih linija, kako bi se kreirala glatka podloga za dalje nanošenje i dugotrajnost šminke.",
    slika: "images/slika95.webp",
  },
  {
    id: 96,
    naziv_proizvoda: "Velnea 3D Masažer za lice i telo",
    kategorija: "lice",
    podkategorija: "čistači i masažeri",
    cena: 1499.99,
    opis: "Vaša omiljena spatula za nanošenje kreme i masažer za predeo oko ociju u jednom proizvodu – sacuvajte vašu kremu od bakterija, nežno umasirajte antirid i podstaknite cirkulaciju.",
    slika: "images/slika96.webp",
  },
  {
    id: 97,
    naziv_proizvoda:
      "Baby Boo prirodna i organska krema za lice sa manuka medom 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 989.99,
    opis: "Hranljiva krema za negu osetljive kože lica, obogaćena ekstraktom manuka meda.Pakovanje sadrži 50ml.",
    slika: "images/slika97.webp",
  },
  {
    id: 98,
    naziv_proizvoda:
      "Lierac Supra Radiance gel krema za regeneraciju i detoksikaciju normalne i mešovite kože 50ml",
    kategorija: "lice",
    podkategorija: "krema",
    cena: 8089.99,
    opis: "Istražujući ishranu i okruženje, Lierac je otkrio protein NRF 2 koji je osnova Supra Radiance dermokozmetičke linije kao prva nega koja se bazira na regeneraciji kože i povratku blistavosti uz tri inovacije: Detoks ćelija, blistava koža i korekcija bora. NRF 2 PROTEIN vrši detoksikaciju ćelija (eliminiše toksine, sprečava antioksidaciju) i ćelijsku reaktivaciju (reaktivacija ćelijskog metabolizma)",
    slika: "images/slika98.webp",
  },
  {
    id: 99,
    naziv_proizvoda: "Lierac gelasti losion za čišćenje lica 200ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 2479.99,
    opis: "Dvostruki efekat ovog losiona - završnica čišćenja i sužavanje pora - pruža potpuno novo iskustvo. Čim se gel nanese na kožu, on se pretvara u vodu koja lako klizi niz kožu - poput gela. Bez lepljivog osećaja, na koži ostaje samo osežaj čistoće i svežine. Eufrazija, biljka poznata po svojim medicinskim svojstvima, smanjuje iritacije i sadrži tanine koji deluju astigentno pa su pore na koži manje vidljive.",
    slika: "images/slika99.webp",
  },
  {
    id: 100,
    naziv_proizvoda: "Lierac penasta krema za čišćenje lica 150ml",
    kategorija: "lice",
    podkategorija: "umivalica",
    cena: 2479.99,
    opis: "Kremasta pena - ili penasti krem sadrži visok sadržaj ulja koja pomažu da krem klizi po koži i omogući masažu. U kontaktu sa vodom, krem se pretvara u laku prozračnu penu koja se lako ispira sa kože, uz osećaj čistoće i svežine. Mlečna kiselina dobijena od šećerne trske istovremeno obezbeđuje hidrataciju svojim svojstvom vezivanja vode, i odstranjivanje izumrlih ćelija.",
    slika: "images/slika100.webp",
  },
];
